workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
